CONTRIBUTING.md

Added Rajat Bansal to the list

Updating contributions file

---

CONTRIBUTING.md

Submitted Team Role

---

CONTRIBUTING.md

Adding Lan Phan and his role to code-mentoring

Added Lan Phan to the contribute.md

---

packages/client/src/components/LeaderBoardWidget/LeaderBoardWidget.tsx
packages/client/src/pages/Dashboard/Dashboard.page.tsx
packages/ui/components/Card/Card.tsx
packages/ui/css/components/text.css
packages/ui/tailwind.config.js

- Fixed #26
- Added `rounded-circle` class to tailwind
- H4 base styles
- Added border to card

feat: added LeaderboardWidget

---

packages/api/package.json
packages/api/src/Auth/strategies/jwt.strategy.ts
packages/api/src/User/CurrentUser.decorator.ts
packages/api/src/User/User.entity.ts
packages/api/src/User/User.resolver.ts
packages/api/src/schema.gql
yarn.lock

I added me resolver. I had to modify the CurrentUser decorator using decode-jwt to get the user from the token. Not sure if that is the way to handle that with NestJS but I couldn't retrieve the user in the way it was done, and userId and username from the context was coming undefined all time.

Me gql query

---

.eslintrc
package.json
packages/api/src/App.module.ts
packages/api/src/Auth/Auth.resolver.ts
packages/api/src/Auth/Auth.service.ts
packages/api/src/Auth/index.ts
packages/api/src/Auth/strategies/jwt.strategy.ts
packages/api/src/Database.module.ts
packages/api/src/User/CurrentUser.decorator.ts
packages/api/src/User/User.entity.ts
packages/api/src/User/User.resolver.ts
packages/api/src/User/User.service.ts
packages/api/src/User/index.ts
packages/api/src/main.ts
packages/client/src/components/LeaderBoardWidget/LeaderBoardWidget.tsx
packages/client/src/components/Page/Page.tsx
packages/client/src/containers/Auth.container.ts
packages/client/src/containers/Me.container.ts
packages/client/src/containers/Wrapper.tsx
packages/client/src/index.tsx
packages/client/src/lib/apollo.ts
packages/client/src/lib/localStorage.ts
packages/client/src/pages/Dashboard/Dashboard.page.tsx
packages/client/src/pages/Login/Login.page.tsx
packages/client/src/router/AppRouter.tsx
packages/client/src/router/routes.ts
yarn.lock

- Fixes #6 
- Added lint to entire project
- Linted all files
- Added `yarn lint` to check files
- Added `yarn lint:fix` to fix files if it can

feat: added linting

---

packages/ui/tailwind.config.js

- Updated Secondary 900 
- Updated Tertiary 900

feat(ui): added new 900 colors

---

packages/client/src/lib/apollo.ts

- Fixes #51 
- Fixed error created by linting in `apollo.ts` in `client`

fix(client): fixed buld with linting error

---

packages/client/src/components/LeaderBoardWidget/LeaderBoardWidget.tsx

I just added mb-2 class in the div tag to have space between users.

fix(client): add mb-2

---

.eslintrc
.github/workflows/ci.yml
.gitignore
package.json
packages/api/config/test.yml

- Fixes #7
-  Disabled "linebreak-style" lint - there were many files failing on the Windows CI
- Added ci.yml for on push/PR CI actions
- Added "test" script to root
- Fixed some lint errors

Feature/setup ci GitHub actions

---

packages/api/src/Database/index.ts
packages/api/src/Database/seeders/Seeders.service.ts
packages/api/tests/utils/TestClient.ts

fix(api): seeders

---

packages/api/src/Database/Database.service.ts

fixes: #64 
Added **seeders** to comment in DANGEROUSLY_RESET_DATABASE fn

fix: add seeders to comment in reset dabatase fn

---

.github/workflows/ci.yml
.gitignore
package.json
packages/api/codecov.yml
packages/api/package.json
yarn.lock

- Fixes #65 
- Added github action for codecov push

ci: added codecov action

---

docker-compose.yml

- Fixes #88 
- Added PGDATA inside docker-compose.yml under environment.

fix(api): added PGDATA inside docker-compose

---

packages/api/src/Database/seeders/Seeders.service.ts

- Fixes #100 
- Added userProfile to seed user

feat(api): add user profile to user in seeders

---

CONTRIBUTING.md

updated contributor list

---

packages/ui/css/components/buttons.css
packages/ui/css/components/text.css
packages/ui/lib/classes.ts

Added some small style changes for WWW signup

style(ui): small style changes

---

CONTRIBUTING.md

- Fixes #ISSUE_1
- Fixes #ISSUE_2
- Change 1
- Change 2
- Change 3

Sign up (Balkirat Singh)

---

packages/client/src/containers/Me.container.ts

- Fixes #148 
- Removed duplicate userPreferences query

fix(client): removed duplicate query

---

packages/client/src/components/AppHeader/AppHeader.tsx
packages/client/src/components/SignOutBtn/SignOutBtn.module.css
packages/client/src/components/SignOutBtn/SignOutBtn.tsx

Fixes #115
- Add a Sign Out Button component allow the user to sign out
- Redirect the user to the login page
- Alert the user they have signed out by using console.log()
- Addition of SignOut file in src/components with SignOutBtn.tsx and SignOutBtn.module.css files
- Displaying the button at the AppHeader component for functionality

User Signing out - Client
